apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: flow
  namespace: logging
spec:
  match:
    - select:
        labels:
          run: logs
        namespaces:
          - default
