apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterOutput
metadata:
  name: file-output
  namespace: logging
spec:
  file:
   path: /tmp/logs/${tag}/%Y/%m/%d.%H.%M
   append: true
   buffer:
     timekey: 1m
     timekey_wait: 10s
     timekey_use_utc: true
