apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF6TURRdwpPVEExTWpSYUZ3MDBNekF6TURRd09UQTFNalJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUmtvWEN3NFJRdmIyN00wa1d5M0pLYUhRcUcrY2xhbHpYckNyYXVWYktwMjQ5cmx2Sgo4TVNTU3M1WmVnb05aRWdFejFyVGVsbE9LY1lyVmZxWVhNMGw5aHgyZ0hldVRJMlNUSmR2anpwMUVRZGNOTG5pCjFyenUrVkYyb05paEUvL3hDOTJPZ2loNGVxNG1lc1NhQ2hOQ043Tk1aYit3S043OFU5dzFtdnE0c3FCRzJUTFQKOGVyNkVRT09XNnNaSkpBQjZhVUhGcVdPenpUc0dXS0NHL2p6czJpaW56NVhzSjZtK21NSnZ4eFBiUUV1T0JWVAowMS9GZnJQRUlsTkxmaVk1eTUxb1dFbVJxWHJvUkZGS3RVRktKUE1nQTU0WmpzQVhKdzZIL1poamdQVTRQSXl1CkpycjBITUFjOTlLNSs2ZHMxbFQvdFNFcTFvZFVYWnRMMlVaUkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRneUpaZ3duZVdTMUhTVTljdgpyUjZQdUk3OU9qQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFnTmNKM1plcWZiRDJ4RlhYcC9FQkhCejVkb2RQCkdTMkdObnVIUXZFSTRSV2orZjY2V1dPMWNMdHd1Z0JhWlRrZy95czFuOGpDd1FBTDEyeVJEWWl4ZVZaRzB0bTQKeTlibDRVdE9mRVdHSzBaQWVvZmFyWkZvVkxIZk5MbjdxUGgyVUVsQmpZT3VBc21jMUFQQ2lyNDNTOGVYcXh3ZwpHc2ZNOE5GWnU2VzhzYjk0bHlNNHpzYUd1dTdHTVJ0bGFqaDhTODZyVTRqeVd3VmdrS0lDQlNOUmJ2UlBrQkNpCmNnSVBtRnhmNTJjKy94SDFFLzBLWHp3U01XcnlBNDFsaGxDRHFqRWJub0FhRU44UlUzejg1d3pSZFA2K3lwbWYKNGdLUnpsUkZKcGtHR3I1MHVweXZuWkdOZVBzUlFDRGpkcjkvNmNEdnRXMzV3RDJMOS9LdVd2UGFRQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://bd653794-d65a-478e-a822-65e96c593d48.k8s.ondigitalocean.com
  name: do-fra1-k8s
contexts:
- context:
    cluster: do-fra1-k8s
    user: do-fra1-k8s-admin
  name: do-fra1-k8s
current-context: do-fra1-k8s
kind: Config
preferences: {}
users:
- name: do-fra1-k8s-admin
  user:
    token: dop_v1_4eba9623a32b277db1f52298f2f40d54d1cd71ceab371ded3bbe6f0aa25a255b
