apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
 name: demo-output
spec:
 file:
   path: /tmp/logs/${tag}/%Y/%m/%d.%H.%M
   append: true
   buffer:
     timekey: 1m
     timekey_wait: 10s
     timekey_use_utc: true
