---
- name: wait for ssh connection
  hosts: all
  gather_facts: False
  tasks:
    - name: ensure ssh port connection
      wait_for:
        port: 22
        delay: 10
        timeout: 100
        search_regex: OpenSSH
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local

